### PR TITLE
feat: adding batch display on enter

### PR DESCRIPTION
**Pull request by jeff06**
If outputmirror is set, and there is a batchsize that has been set (SetBatchSize(6)), element will be displayed according to this. This exclude header and footer.

### CODE REVIEW

**Comment by jedib0t** [comment]
Thanks for the contribution. But I feel there may be a better way to do this without changing existing interfaces. Give me a few days to think about this. Busy with real world stuff. :(

**Comment by jeff06** [comment]
Hello, 

Hope everything is ok.
I was Curious about the status of this PR.

Thank,

**Comment by jedib0t** [comment]
Hey really sorry about the delay. I started working on an alternate implementation last week that would give you a "Pager" which will let you go back and forth in pages. But I never got around to completing it due to personal reasons. I promise to get back to you by this weekend. 🤞

**Comment by jedib0t** [comment]
Hey @jeff06 sorry for the delay. I've pushed an initial draft of my changes to the `pager` branch @ https://github.com/jedib0t/go-pretty/tree/pager. Specific commit: https://github.com/jedib0t/go-pretty/commit/d2e7d2493480beb88a7755619ab33687ceb4c8cd -- please take a look and let me know if this serves your purpose. I'll then merge it to the main branch.

**Comment by jeff06** [comment]
Hi, Yes it does, thank you so much

**Pull request closed without merging**
