### PR TITLE
progress: add incremental failure mode

### LINKED ISSUE #159: progress: would like to indicate error before completion
**Is your feature request related to a problem? Please describe.**

Let's say I have 100 pieces of a task, each piece takes 10 seconds to accomplish, and I can do them concurrently. If one of them fails, I'd like to tell the user that one of them has failed, but the others are still making progress.

**Describe the solution you'd like**

It would probably be best to let the tracker continue, and update the tracker message to indicate that an error occurred. Currently `Tracker.Message` is public, but (even though not documented as such) probably shouldn't be written after a tracker is started because string assignment isn't guaranteed to be atomic (https://groups.google.com/g/golang-nuts/c/UWJlS8mPTlM). 

Adding a mechanism to update the tracker message (and/or color) would work nicely. The user would still need to finalize the tracker via `MarkAsErrored`. What do you think?

... yes, I know I added MarkAsErrored, but clearly I didn't actually think through what I really wanted before doing that. :)

### PR DESCRIPTION
**Pull request by virtuald**
Thought about it, looks like changing the message is likely to be difficult, so I'm just going to highlight it instead. Changes SetValue behavior but I think that's fine since it's a relatively new change?

Fixes #159

### CODE REVIEW

**Comment by jedib0t** [comment]
I feel that we are stepping into over engineering a solve here for a problem that may never show up. I use this library in a private project where the Message is changed as part of the execution based on where the activity is at. And used by more than a few hundred folks on a daily basis. I understand this is a personal anecdote and may not reflect your observations.

The only place the message is used is to render the text on the screen, and this gets updated more than a few times a second with the default setting so this should not cause any noticeable issues to warrant all these changes. You should be able to change the Message including coloring it manually with something along the lines of:
```golang
tracker.Message = text.Red.Sprint("oops this thing failed!")
```

If you do see issues with changing the Message value, please share a code sample and we can go from there.

**Comment by virtuald** [comment]
The race detector really doesn't like it when you change tracker.Message during execution, see #161  for a demonstration.

**Comment by jedib0t** [comment]
I'm sure there will be a race condition here since the value is being read and written at the same time, but is it affecting the functionality adversely? Even if the message is not updated on screen immediately, it will be in the next render pass.

Regardless, I feel something like `tracker.UpdateMessage()` would be a cleaner approach to minimize races (not remove it altogether). Or making `Message` private and introducing a `tracker.SetMessage()` to remove races altogether.

**Comment by virtuald** [comment]
In any case, this PR is not proposing to change tracker.Message (which because of semver would require an upgrade to v7.x?). This is merely making it possible to mark a progress bar as an error before it completes, which seems like a pretty reasonable thing to do. The only part that's a particularly complex addition would be the demo -- but I could remove that if you want.

**Comment by jedib0t** [comment]
Yes that would require a major version bump. 😢 

As for this PR: I'm okay with the change. But, can you please revert the demo changes, and add a unit-test for the new function in tracker_test.go?

**Comment by virtuald** [comment]
Done, thanks!

**Review by jedib0t — APPROVED** [review]

**Pull request merged**
