### PR TITLE
feat: progress speed

### PR DESCRIPTION
**Pull request by iyear**
## Proposed Changes
  - add progress speed render
  - modify `render_test.go`
  - modify demo and `demo.gif`

### CODE REVIEW

**Comment by iyear** [comment]
I will add some tests later

**Comment by jedib0t** [comment]
Thanks for the feature, and the extra effort to keep the coverage at 100%. I'll merge it, but I want to add some stuff on top. Will cut a tag later today. 👍🏽

**Comment by jedib0t** [comment]
@iyear I've made some changes on top of your feature code, most important of which is to change the default options to NOT show speed to maintain backward compatibility. Please look at #225 for the same.

Tag for use: https://github.com/jedib0t/go-pretty/releases/tag/v6.3.8

**Comment by iyear** [comment]
I wasn't thinking about backward compatibility, thanks!

**Pull request merged**
