### PR TITLE
text: Remove dependency on github.com/go-openapi/strfmt

### PR DESCRIPTION
**Pull request by titanous**
This is a non-breaking change that removes the dependency on `github.com/go-openapi/strfmt`. Formatting a `strfmt.DateTime` still works, though the format is different.

This removes a large set of indirect dependencies, including a MongoDB driver.

### CODE REVIEW

**Comment by jedib0t** [comment]
Hey thanks for the PR. Really appreciate the contribution. I totally agree that all these dependencies should be removed and need not be part of `go-pretty`. Definitely not a MongoDB driver of all things!

I'm curious about the test failures. These tests start failing only when you remove this block of code:
```golang
		if valDate, ok := val.(strfmt.DateTime); ok {
			rsp = formatTime(time.Time(valDate))
		}
```
Which is to be expected as the code the unit-tests were exercising is no more. Removal of the above code results in `transformer(inDateTime)` not parsing the input at all and just returning the value computed by `rsp := fmt.Sprint(val)`. You can see this if you step through a debugger.

I don't mind removing `strfmt.DateTime` support from `NewTimeTransformer` as this honestly just an example that folks can use to build their own custom transformers. Give me a day or two to see if there is any way to support it without including it. If I don't have any recommendations in a couple of days, I'll merge this PR.

**Comment by titanous** [comment]
Ah! I was fiddling with it and must not have saved the file before re-running the tests. Sounds good, thanks!

**Comment by jedib0t** [comment]
Hey @titanous ... I've merged your changes.

I'll add one more fix on top later today to support `strfmt.DateTime` indirectly. The current code will not handle `strfmt.DateTime` objects since `val.(time.Time)` does not work for `strfmt.DateTime` even though both are similar.

**Comment by titanous** [comment]
Awesome, thanks!

**Comment by jedib0t** [comment]
Hey @titanous ... please take a look at changes made in #123 and lemme know if you see any issues.

I've cut a new release that you can use: https://github.com/jedib0t/go-pretty/releases/tag/v6.0.3

Once again, thanks for the contribution! 🎉

**Comment by titanous** [comment]
LGTM! Thanks!

**Pull request merged**
