### PR TITLE
progress: add pin message

### PR DESCRIPTION
**Pull request by iyear**
## Proposed Changes
Add pin message for progress bar, It will be displayed at the top of all active trackers.

Developers can display some dynamic information here (e.g. CPU, load, memory)

### CODE REVIEW

**Comment by jedib0t** [comment]
I like this feature and I see how this can be useful, but I think the interfaces can be finessed a bit more. I'll accept this change and deliver one more change on top to change the interfaces/keyboard a bit.

**Comment by jedib0t** [comment]
@iyear I've published a new release with support for Pinned messages that you contributed. Made some changes on top, but it contains the essence of what you designed: https://github.com/jedib0t/go-pretty/releases/tag/v6.4.0

**Comment by iyear** [comment]
@jedib0t More beautiful and elegant, thank you!

Please forgive my poor English XD.

**Comment by jedib0t** [comment]
> @jedib0t More beautiful and elegant, thank you!
> 
> Please forgive my poor English XD.

Hey your English is fine. I really appreciate the contribution! 👍🏽

**Pull request merged**
